import json
import os
from dotenv import load_dotenv
from langchain_openai import AzureChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.output_parsers.json import SimpleJsonOutputParser as JsonOutputParser


load_dotenv()


ENDPOINT = "https://deyoze-tech-resource.services.ai.azure.com/"
DEPLOYMENT_NAME = "grok-3"  
API_KEY = os.environ.get("AZURE_API_KEY")
API_VERSION = "2024-05-01-preview"  

# 1. Set up the LangChain LLM
llm = AzureChatOpenAI(
    openai_api_version=API_VERSION,
    azure_deployment=DEPLOYMENT_NAME,
    azure_endpoint=ENDPOINT,
    openai_api_key=API_KEY,
    temperature=0
)

# 2. Define the prompt template
prompt_template = ChatPromptTemplate.from_template("""
You are an expert evaluator for student programming exams. Your task is to:

1. Compare the student's answer to the ideal answer.
2. Provide a score from 0 to 2(inclusive), where the score cannot be a decimal values.
3. Give full score if the idea is clear in the answer.

**Important Instructions:**
- The question and student's answer may be in English, Malayalam, or a mix of both languages.
- Do NOT consider language, grammar, spelling, presentation style, or capitalization while scoring.
- Focus only on the correctness of the logic, structure, and content.

**Question:** 
{question}

**Ideal Answer**
{ideal_answer}

**Student's Answer:** 
{student_answer}

**Provide your response strictly in the following JSON format:**

{{
  "ideal_answer": "<ideal correct answer generated by you>",
  "score": <score out of 2>
}}
""")

# 3. Define the evaluation function using LangChain
def check_answer_langchain(question, student_answer, ideal_answer):
    chain = prompt_template | llm | JsonOutputParser()
    try:
        result = chain.invoke({
            "question": question,
            "student_answer": student_answer,
            "ideal_answer": ideal_answer
        })
    except Exception as e:
        result = {"error": str(e)}
    return result


def process_assessment(student_assessment_id=None):
    questions = [
        {
            "id": 1236,
            "question": "What is a IP address, Also which are the two type of IP address?",
            "ideal_answer": "An IP address, which stands for Internet Protocol address, is a numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication. IP addresses serve two main purposes: host or network interface identification and location addressing. A public IP address is a globally unique address assigned to a device on the internet. It is provided by the Internet Service Provider (ISP) and serves as the device's identity on the worldwide web. A private IP address is used within a local network and is not directly accessible from the internet. Devices within the same local network share private IP addresses.",
            "answer": "Internet is some protocol used in legal side of internert. two types are protocol are there which are internal and external"
        },
        {
            "id": 1237,
            "question": "what is a web server? give a example?",
            "ideal_answer": "A web server is software or hardware that stores, processes, and delivers web pages to users over the internet.One example of a web server software is Apache HTTP Server.",
            "answer": "In Internet oru website, app, etc hosting place"
        },
        {
            "id": 1238,
            "question": "what is internet?",
            "ideal_answer": "The internet, short for interconnected networks, is a global network that connects millions of private, public, academic, business, and government networks. It is a vast and decentralized network of networks that use standardized communication protocols to enable the exchange of information and data worldwide.",
            "answer": "internet is network used to connect things everywhere or globaly, You can use it to connect many peoples, private poeple can connect together personally, public connection is available, it is used for business, studying and also for entertainment etc..."
        },
        {
            "id": 1239,
            "question": "what is DNS?",
            "ideal_answer": "DNS stands for Domain Name System. It is a hierarchical and decentralized naming system used to translate human-readable domain names into IP addresses and vice versa.",
            "answer": "ഡൊമെയിൻ നാമം ഐപി അഡ്രസായി മാറ്റുന്ന സംവിധാനമാണ് DNS."
        },
        {
            "id": 1240,
            "question": "what is find() method?",
            "ideal_answer": "The find() method returns descendant elements of the selected element. A descendant is a child, grandchild, great-grandchild, and so on... To return or to find all of the descendant elements, use the * selector.",
            "answer": "The find() method returns descendant elements of the selected element. A descendant is a child, grandchild, great-grandchild, and so on..."
        }
    ]

    results = []
    for q in questions:
        evaluation = check_answer_langchain(q["question"], q["answer"], q["ideal_answer"])
        results.append({
            "id": q["id"],
            "question": q["question"],
            "ideal_answer": q["ideal_answer"],
            "student_answer": q["answer"],
            "evaluation": evaluation
        })
    return results


if __name__ == "__main__":
    # Example usage of process_assessment
    print("\n=== Example: process_assessment (LangChain) ===")
    assessment_results = process_assessment(1236) 
    for res in assessment_results:
        print(json.dumps(res, indent=2, ensure_ascii=False))
